name: NextRelease
on:
  push:
    branches:
     - 'develop'
jobs:
  action-pull-request:
    runs-on: ubuntu-24.04

    concurrency:
      cancel-in-progress: true
      group: release-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.1
        with:
          github_token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
          title: 'Next release'
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          target_branch: main
          label: automatic,release
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
