name: NextRelease
on:
  push:
    branches:
     - 'develop'
permissions:
  contents: read
  pull-requests: write
jobs:
  action-pull-request:
    runs-on: ubuntu-24.04
    environment: release

    concurrency:
      cancel-in-progress: true
      group: release-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.1.0
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Next release'
          assignee: ${{ github.actor }}
          target_branch: main
          label: automatic,release
          new_string: ${{ github.event.head_commit.message || github.sha }}
          get_diff: true
